apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: bl-scale-sched
    name: bl-scale-sched
spec:
    replicas: 1
    selector:
        matchLabels:
            app: bl-scale-sched
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: bl-scale-sched
        spec:
            containers:
            - env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "/var/run/secret/cloud.google.com/bl-scale_key.json"
                - name: STAGE
                  value: PROD
              volumeMounts:
              - name: "cred-key"
                mountPath: "/var/run/secret/cloud.google.com"
              image: gcr.io/breakthrough-listen-sandbox/bl-scale:scheduler-stable
              imagePullPolicy: Always
              name: bl-scale-sched
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              ports:
              - containerPort: 6443
            volumes:
              - name: "cred-key"
                secret:
                  secretName: "bl-scale-cred-key"
            nodeSelector:
                cloud.google.com/gke-nodepool: webapp-pool
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
