name: Google App Engine Deployment
# For this to work, you must verify the App Engine Admin API is enabled.
on:
  push:
    branches: [ master, stable ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieving the repo
        uses: actions/checkout@v2
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip && cd webapp && pip install -r requirements.txt

      - name: "Deploy to App Engine"  
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{secrets.B64_GCP_JSON_KEY }}
        with:
          args: app deploy --version=${{ steps.extract_branch.outputs.branch }} --no-stop-previous-version webapp/app.yaml
