# This is a basic workflow to help you get started with Actions

name: Build Monitor and Proxy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ stable ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # - name: Build and push Web App Image to Google Container Registry
    #   uses: docker/build-push-action@v1
    #   with:
    #       username: _json_key
    #       password: ${{ secrets.GCP_JSON_KEY }}
    #       registry: gcr.io
    #       repository: breakthrough-listen-sandbox/bl-scale
    #       dockerfile: dockerfiles/webapp.dockerfile
    #       tags: webapp-latest

    # - name: Build and push Web App Test Image to Google Container Registry
    #   uses: docker/build-push-action@v1
    #   with:
    #       username: _json_key
    #       password: ${{ secrets.GCP_JSON_KEY }}
    #       registry: gcr.io
    #       repository: breakthrough-listen-sandbox/bl-scale
    #       dockerfile: dockerfiles/webapp-test.dockerfile
    #       tags: webapp-test-latest

    - name: Build and push Scheduler Image to Google Container Registry
      uses: docker/build-push-action@v1
      with:
          username: _json_key
          password: ${{ secrets.GCP_JSON_KEY }}
          registry: gcr.io
          repository: breakthrough-listen-sandbox/bl-scale
          dockerfile: dockerfiles/scheduler.dockerfile
          tags: scheduler-stable

    - name: Build and push Monitoring Image to Google Container Registry
      uses: docker/build-push-action@v1
      with:
          username: _json_key
          password: ${{ secrets.GCP_JSON_KEY }}
          registry: gcr.io
          repository: breakthrough-listen-sandbox/bl-scale
          dockerfile: dockerfiles/monitor.dockerfile
          tags: monitor-stable

    # Runs a single command using the runners shell
    - name: Build and push Monitoring Image to dockerhub
      uses: docker/build-push-action@v1
      with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: fx196/bl-scale
              dockerfile: dockerfiles/monitor.dockerfile
              tags: monitor-stable

    - name: Build and push Proxy Image to Google Container Registry
      uses: docker/build-push-action@v1
      with:
          username: _json_key
          password: ${{ secrets.GCP_JSON_KEY }}
          registry: gcr.io
          repository: breakthrough-listen-sandbox/bl-scale
          dockerfile: dockerfiles/zproxy.dockerfile
          tags: zproxy-stable

    # # Runs a single command using the runners shell
    # - name: Build and push Web App Image to dockerhub
    #   uses: docker/build-push-action@v1
    #   with:
    #           username: ${{ secrets.DOCKER_USERNAME }}
    #           password: ${{ secrets.DOCKER_PASSWORD }}
    #           repository: fx196/bl-scale
    #           dockerfile: dockerfiles/webapp.dockerfile
    #           tags: webapp-latest

    # # Runs a single command using the runners shell
    # - name: Build and push Web App Test Image to dockerhub
    #   uses: docker/build-push-action@v1
    #   with:
    #           username: ${{ secrets.DOCKER_USERNAME }}
    #           password: ${{ secrets.DOCKER_PASSWORD }}
    #           repository: fx196/bl-scale
    #           dockerfile: dockerfiles/webapp-test.dockerfile
    #           tags: webapp-test-latest
