name: Build Webapp

on:
  push:
    branches: [ stable ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build and push Web App Image to Google Container Registry
      uses: docker/build-push-action@v1
      with:
          username: _json_key
          password: ${{ secrets.GCP_JSON_KEY }}
          registry: gcr.io
          repository: breakthrough-listen-sandbox/bl-scale
          dockerfile: dockerfiles/webapp.dockerfile
          tags: webapp-stable

    # Runs a single command using the runners shell
    - name: Build and push Web App Image to dockerhub
      uses: docker/build-push-action@v1
      with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: fx196/bl-scale
              dockerfile: dockerfiles/webapp.dockerfile
              tags: webapp-stable

    # Runs a single command using the runners shell
    - name: Build and push Web App Test Image to dockerhub
      uses: docker/build-push-action@v1
      with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: fx196/bl-scale
              dockerfile: dockerfiles/webapp-test.dockerfile
              tags: webapp-test-stable
